major reorg: rename pathmunge to pathfilter; common code in common.sh; fallback pathfilter shell function

diff --git a/profile-dir/dot-bashrc b/profile-dir/dot-bashrc
--- a/profile-dir/dot-bashrc
+++ b/profile-dir/dot-bashrc
@@ -8,43 +8,20 @@ if [ -f /etc/bashrc ]; then
 	source /etc/bashrc
 fi
 
-# XDG Base Directory paths
-# defined in https://specifications.freedesktop.org/basedir-spec/latest/
-function xdg_base_set
-{
-    xdg_var="$1"
-    xdg_path="$2"
-    if [ ! -d "$xdg_path" ]
-    then
-        mkdir -p "$xdg_path"
-    fi
-    if [ -z "${!xdg_var}" ] # ! = use indirection to read var named by a var
-    then
-        eval "${xdg_var}=$xdg_path"
-        eval "export ${xdg_var}"
-    fi
-}
-xdg_base_set XDG_CONFIG_HOME "${HOME}/.config"
-xdg_base_set XDG_CACHE_HOME "${HOME}/.cache"
-xdg_base_set XDG_DATA_HOME "${HOME}/.local/share"
-xdg_base_set XDG_STATE_HOME "${HOME}/.local/state"
-
-# point BASHRC_DIR at .config/sh/bashrc.d and SH_PROFILE_DIR at .config/sh/profile.d
-# (following XDG Base Directory Specification to declutter home dot-files)
-SH_CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}"/sh
-BASHRC_DIR="${SH_CONFIG_DIR}/bashrc.d"
-SH_PROFILE_DIR="${SH_CONFIG_DIR}/profile.d"
-export BASHRC_DIR SH_PROFILE_DIR
-
-# point to pathmunge.pl which can be used by multiple profile.d scripts
-PATHMUNGE="${SH_CONFIG_DIR}"/pathmunge
-if [ ! -x "${PATHMUNGE}" ]
+# get common functions used by both .bashrc and .profile
+common_sh="$HOME/.config/sh/common.sh"
+if [ ! -e "${common_sh}" ]
 then
-    # fallback in case of any problem with pathmunge (which should symlink to either Perl or Rust implementation)
-    # this fallback function is less capable: like pathmunge of stock Linux distros, it doesn't do deduplication
-    :
+    echo ".bashrc aborting due to incomplete installation: ~/.config/sh/common.sh not found" >&2
+    return 1 # do not use exit here because it will exit the shell, including login shells
 fi
-export PATHMUNGE
+# shellcheck source-path=~/.config/sh disable=SC1090,SC1091
+source "${common_sh}"
+
+# point BASHRC_DIR at .config/sh/bashrc.d
+# (following XDG Base Directory Specification to declutter home dot-files)
+BASHRC_DIR="${SH_CONFIG_DIR}/bashrc.d"
+export BASHRC_DIR
 
 # make sure BASHRC_DIR existS
 if [ ! -d "$BASHRC_DIR" ]
diff --git a/profile-dir/dot-profile b/profile-dir/dot-profile
--- a/profile-dir/dot-profile
+++ b/profile-dir/dot-profile
@@ -4,14 +4,15 @@
 # note: for interactive non-login shells, bash runs ~/.bashrc instead
 # by Ian Kluft
 
-# point SH_PROFILE_DIR to .config/sh/profile.d
-SH_CONFIG_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}"/sh
-SH_PROFILE_DIR="${SH_CONFIG_DIR}"/profile.d
-export SH_PROFILE_DIR
-
-# point to pathmunge.pl which can be used by multiple profile.d scripts
-PATHMUNGE="${SH_CONFIG_DIR}"/pathmunge
-export PATHMUNGE
+# get common functions used by both .bashrc and .profile
+common_sh="$HOME/.config/sh/common.sh"
+if [ ! -e "${common_sh}" ]
+then
+    echo ".profile aborting due to incomplete installation: ~/.config/sh/common.sh not found" >&2
+    return 1 # do not use exit here because it will exit the shell, including login shells
+fi
+# shellcheck source-path=~/.config/sh disable=SC1090,SC1091
+. "${common_sh}"
 
 # make sure SH_PROFILE_DIR exists
 if [ ! -d "$SH_PROFILE_DIR" ]
@@ -61,4 +62,4 @@ do
 done
 
 # clean up variables no longer needed after running profile.d scripts
-unset PATHMUNGE
+unset PATHFILTER
